spring:
  application:
    name: my-kipawa-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/mykipawa}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWJhc2U2NC1lbmNvZGVkLXNlY3JldC1rZXktd2l0aC0yNTYtYml0cw==}
  expiration: ${JWT_EXPIRATION:86400000}